Tutorial page translated!
reactjs/fa.reactjs.org pull request #159
Opened 2020-07-05 12:04 UTC by amirmahdi-nsh

😎
> Note
> This is my work account(my personal account is amir28 :))

2020-07-05 16:06 UTC, sorousht commented
Hi @amirmahdi-nsh!

Thanks for your great work! Since we have a few open PRs, please give me some time to wrap them up one-by-one, and then I review your PR.

Best regards,
Soroush

2020-07-26 16:06 UTC, sorousht commented on content/tutorial/tutorial.md
> +لازم به ذکر است که در طول این آموزش ما بازی کوچکی می‌سازیم و از شما خواهشمندیم حتا اگر قصد بازی سازی ندارید از آن سرپوشی نکنید. زیرا که تکنیک‌های مورد استفاده در این آموزش و این بازی، پایه و اساس برن
```suggestion
در طول این آموزش، ما یک بازی کوچک خواهیم ساخت. ممکن است شما قصد داشته باشید که از آن [خواندن] آن صرف‌نظر کنید،چون شما بازی نمی‌سازید، اما به آن فرصت دهید. تکنیک‌هایی که در این آموزش فرا می‌گیرید، مبانی ساخت هر برنامه ری‌اکت است و تبحر در آن می‌تواند به شما درک عمیقی از ری‌اکت می‌دهد.```

2020-07-26 19:52 UTC, amirmahdi-nsh commented on content/tutorial/tutorial.md
> +title: "مقدمه‌ای بر ری‌اکت"
اگه امکانش هست یه فاصله بعد "آموزش:" باشه بهتره :)

2020-07-27 04:57 UTC, amirmahdi-nsh commented
<p dir='rtl' align='right'>سلام سروش عزیز @sorousht </p>
<p dir='rtl' align='right'>تغییراتی که پیشنهاد دادید کاملا به جا و درست بود. اما از این که در کل متن دقیقا شبیه به متن انگلیسی باشد انتقاد دارم</p>
<p dir='rtl' align='right'>من در هنگام این آموزش خودم هم در حال ترجمه هم در حال یادگیری بودم یعنی اول نسخه‌ی انگیلیسی رو می‌خوندم یاد میگرفتم بعد همون رو به فارسی ترجمه می‌کردم. و این کار باعث شد بتونم خودم رو جای خواننده بزارم و تک‌تک مشکلات اون‌ها رو درک کنم</p>
<p dir='rtl' align='right'>برای مثال من سر Why Immutability Is Important نزدیک به یک هفته مونده بودم. چون نه کاملا می‌فمیدم چیه و نه می‌تونستم بخاطر ترجمه‌ی فارسی از کنارش بگذرم و نادیده بگیرمش</p>
<p dir='rtl' align='right'>‌نفهمیدن من واسه این بود که به کلمه‌ی reference دقت نکرده بودم. و منظورش از اون مکان حافظه‌ی متغییر بود. بنابر این من سعی کردم بر خلاف نسخه‌ی انگیلیسی کامل‌تر توضیح‌ش بدم تا کسی مثل من اون‌جا گیر نکنه.
اگه دقت کنید من حتا مثال هم براش قرار دادم چون اگه اون مثال رو کسی در هنگام ترجمه به من نشون می‌داد خیلی راحت می‌تونستم بفهمم قضیه چیه. </p>
<p dir='rtl' align='right'>مثال دیگرش هم باز تو همون قسمت در Determining When to Re-Render in React است</p>
<p dir='rtl' align='right'>توی نسخه‌ی انگیلسی گفته شده Mutation یا بدون Mutation در این کد بالا نتیجه یکسانی دارند اما بدون Mutation فوایدی دارد(که کار پیاده‌سازی فیچرهای آینده را آسان‌تر می‌کند). اما من به عنوان یک یادگیرنده اومدم و امتحان کردم و دیدم بدون Mutation بر خلاف چیزی که تو نسخه‌ی انگیلسی گفته شد، برنامه کار نمی‌کنه. پس بعد سرچ و دباگ کردن فهمیدم مشکل چیه تو اون رو تو متن آوردم.</p>
<p dir='rtl' align='right'>به همین دلایل معتقدم عین همون متن اینگیلیسی رو به فارسی ترجمه کردن در برخی موارد باعث می‌شه مفهوم به خوبی به کاربر منتقل نشه و کاربر گیج و سردرگم بشه.</p>
<p dir='rtl' align='right'>ممنون</p>

2020-10-04 10:24 UTC, amirmahdi-nsh commented
@sorousht کاری از دست من بر میاد بتونم انجامش بدم؟

2020-10-04 15:25 UTC, sorousht commented
<p dir="rtl">
سلام @amirmahdi-nsh عزیز
</p>

<p dir="rtl">
عذرخواهی می‌کنم که پول‌ریکوست شما مدت خیلی زیادی باز مانده و دلیل اون فقط گرفتاری من بوده است. باید دوباره بررسی کنم. درمورد توضیحات شما باید بگم که هنوز فکر می کنم صحیح نیست که با متن انگلیسی مغایرت وجود داشته باشد. اگر مفهومی در متن بیان شده که به گوش خواننده آشنا نیست، وظیفه خواننده هست که تحقیق کند و درک درستی از آن پیدا کند. 
</p>

<p dir="rtl">
این اسناد به زبان های مختلف دیگری هم ترجمه شده است. تصور کنید که هر زبان مواردی را کم یا اضافه کند. آن وقت ناهماهنگی به وجود  خواهد آمد و همچنین نگاه‌داری از این اسناد و به روز نگه داشتن آن هم دشوار می شود.
</p>

<p dir="rtl">
از طرف دیگر، به دلیل این که این صفحه "toturial" است، تصمیم گرفته بودم که سخت نگیرم و اگر هم مغایرت کوچکی وجود دارد، به شرط صحیح بودن آن، ایراد نگیرم. ولی حتما باید به نحوی بیان شود که به متن اضافه شده است. برای مثال اگر کلمه ای است که در متن اصلی نیست، باید در [کروشه] قرار گیرد. تا خواننده متوجه شود که برای بهتر شدن متن، مترجم آن را اضافه کرده.
</p>

<p dir="rtl">ممنون از شما، ارادتمند، سروش</p>

2020-10-17 16:35 UTC, sorousht requested changes
<p dir="rtl">
@amirmahdi-nsh عزیز، تغییراتی و اضافاتی که در متن ترجمه شما وجود دارد، بیشتر از آنی هست که من بتونم بدون اصلاح، آن را بپذیرم. از طرفی آنقدر از ترجمه و دقت شما به مفاهیم لذت بردم که واقعا حیف است اگر رها شود. از شما خواهش می کنم که به چند مورد از موارد پیش‌نهاد شده دقت کنید و سعی کنید باقی متن رو با توجه به همین موراد اصلاح کنید.
</p>
<p dir="rtl">
متاسفانه امکان اصلاح تمام متن برای من وجود ندارد و وقت بیشتری از نیاز دارد نسبت به این‌که از اول ترجمه شود.
</p>
<p dir="rtl">
همان طور که پیش از این عرض کردم، متاسفانه اجازه نداریم تا این حد تغییرات وارد متن کنیم. اگر فکر می‌کنید که واقعا این تغییرات نیاز هست، باید برای متن انگلیسی پول ریکوست بفرستید و اگر پذیرفته بشود، ما هم تابع آن هستیم.
</p>

2020-10-17 16:35 UTC, sorousht commented on content/tutorial/tutorial.md
> +یک بازی tic-tac-toe یا همان دوز خودمان. کد نهایی بازی را از [اینجا](https://codepen.io/gaearon/pen/gWWZgR?editors=0010) بررسی کنید. اگر چیزی متوجه نشدید و نحوه‌ی نگارش کدها برایتان ناآشنا بود نگران ن
<p dir="rtl">
بخش چه خواهیم ساخت در سه پاراگراف نوشته شده، لطفا شما هم فرمت نوشته رو حفظ کنید
</p>

2020-10-17 16:35 UTC, sorousht commented on content/tutorial/tutorial.md
> +### پبش‌نیاز‌ها {#prerequisites}
<p dir="rtl">
فرمت بخش پیش‌نیاز‌ها به صورت لیست نیست و لطفا سعی کنید تا حد ممکن مشابه فرمت متن انگلیسی باشد
</p>

2020-10-17 16:35 UTC, sorousht commented on content/tutorial/tutorial.md
> +برای اجرای کدهای ری‌اکت و پیش رفتن با این آموزش از دو روش می‌تونیم اقدام کنید.
```suggestion
دو راه برای انجام این آموزش دارید: می‌توانید کد را در مرورگر بنویسید یا یک محیط توسعه لوکال روی رایانه خود آماده کنید.```

2020-10-17 16:35 UTC, sorousht commented on content/tutorial/tutorial.md
> +### ارتباط با ما {#help-im-stuck}
```suggestion
### کمک، من گیر کردم! {#help-im-stuck}
```

2020-10-17 16:35 UTC, sorousht commented on content/tutorial/tutorial.md
> +اگر تمایل دارید رنگ بندی کدها یا syntax highlighting ادیتور خودتون رو تنظیم کنید، میتوانید این [دستورالعمل‌ها](https://babeljs.io/docs/editors/) را دنبال کنید.
```suggestion
برای تنظیم رنگ‌بندی کدها (syntax highlighting) ویرایشگر خود، ما [این دستورالعمل‌ها](https://babeljs.io/docs/editors/) را پیشنهاد می‌کنیم.```

2020-10-17 16:35 UTC, sorousht commented on content/tutorial/tutorial.md
> +اگر در طول این دوره جایی به مشکل برخوردید به [این جا](https://reactjs.org/community/support.html) رجوع کنید. در مواقع خاص [Reactiflux Chat](https://discord.gg/reactiflux) هم می‌تواند روشی سریع برای ک
```suggestion
اگر به مشکل برخوردید به [منایع کمکی کامیونیتی](https://reactjs.org/community/support.html) رجوع کنید. در مواقع خاص [Reactiflux Chat](https://discord.gg/reactiflux) هم می‌تواند روشی سریع برای کمک گرفتن باشد. اگر جوابی دریافت نکردید، یا پیشرفتی حاصل نید، یک issue ثبت کنید و ما به شما کمک خواهیم کرد.
```

2020-10-17 19:50 UTC, amirmahdi-nsh commented on content/tutorial/tutorial.md
> +اگر در طول این دوره جایی به مشکل برخوردید به [این جا](https://reactjs.org/community/support.html) رجوع کنید. در مواقع خاص [Reactiflux Chat](https://discord.gg/reactiflux) هم می‌تواند روشی سریع برای ک
اینجا بهتر نیست از جامعه ری‌اکت ایران نامی برده شه؟ به این دلیل که ثبت issue برای کسی که فقط قسمت کوچیکی از مطلب رو نفهمیده شاید یکم سخت باشه و ترجیح بده به جای گزارش دادن از اون قسمت بگذره و یا زمانش رو صرف سرچ کردن بذاره درصورتی که واقعا مشکلی در متن بوده اما اگه به این انجمن مشکلش رو می‌گفت و اون‌ها تشخیص می‌دادن که این مشکل متنه ممکن بود اعضا خودشون به ما گزارش دهند یا pull request کنند

2020-10-17 20:01 UTC, amirmahdi-nsh commented
سلام، @sorousht  عزیز چشم تلاش می‌کنم تا حد ممکن قسمت‌های اضافی و غیر ضروری که در متن اصلی نیامده حذف و یا اصلاح کنم.
فقط اینکه مدتی‌ست مشکلات و کار‌های زیادی برایم پیش‌آمده و کارهای انجام نشده‌ی زیادی دارم. به همین دلیل پیشاپیش عذر می‌خواهم اگر انجام تغییرات کمی طول بکشد. ممنونم از شما برای پیگیری‌ها

2020-11-14 08:38 UTC, amirmahdi-nsh commented on content/tutorial/tutorial.md
> +اگر وقت اضافه دارید و یا می‌خواهید مهارت خودتان را در ری‌اکت بسنجید، اینجا چند ایده برای بهبود این بازی وجود دارد که از راحت به سخت مرتب شده‌اند:
در نسخه‌ی انگیلیسی قبل این عبارت دوباره گفته عبارت:
Check out the final result here: **[Final Result](https://codepen.io/gaearon/pen/gWWZgR?editors=0010)**.
آمده، در صورتی که چند خط بالاتر دقیقا همین لینک را قرار داده!

2020-11-14 08:46 UTC, amirmahdi-nsh commented on content/tutorial/tutorial.md
> +در مثال بالا، ماشین از ابتدای لیست مورد نظر شروع می‌کند و آن را درون تابعی دلخواه را درون تابع داده شده قرار می‌دهد (در اینجا این تابع `x => x * 2` است که یک مقدار گرفته و دو برابر آن در خروجی بر می‌
اینجا کمی توضیح اضافه آورده‌ام تا نیاز نباشد کاربر درباره‌ی مپ کردن به جست‌وجو بپدازد
اگه اگر فکر می‌کنید این وظیفه‌ی کابر است که به دنبال این گونه مسائل برود. می‌تواند آن را پاک کنید

2020-11-14 08:50 UTC, amirmahdi-nsh commented on content/tutorial/tutorial.md
> +#### تشخیص تغییرات {#determining-when-to-re-render-in-react}
این قسمت برای خود من گیج کننده بود. و من مدتی زیادی روی این بخش گیر کرده بودم.
بعد از پرس‌وجو از افراد ری‌اکت کار توانستم دلیل آن را پیدا کنم. و بعد آن را در اینجا نیز آن را آوردم

2020-11-14 08:54 UTC, amirmahdi-nsh commented on content/tutorial/tutorial.md
> +اگر کنجکاو هستید میتوانید در متد `handleClick` به جای کد قبلی عبارت `'this.state.squares[i] = 'X;` قرار دهید. مشاهده خواهید کرد بعد از فشردن مربع‌ها هیچ تغییری ایجاد نمی‌شود ولی اگر در تب components،
این قسمت در نسخه‌ی اصلی نیست ولی پیشنهاد می‌کنم که باقی بماند زیرا که کاربر باید بداند با تغییر مستقیم استیت کامپوننت‌های ری‌اکت دوباره رندر نمی‌شود. و دانستن این موضوع در آینده بسیار حیاتی‌ست!

2020-11-14 08:59 UTC, amirmahdi-nsh commented on content/tutorial/tutorial.md
> +>نکته
در نسخه‌ی اصلی این قسمت به صورت نکته ننوشته شده. هر جور صلاح می‌دونید

2020-11-14 09:02 UTC, amirmahdi-nsh commented on content/tutorial/tutorial.md
> +>      <button className="square" onClick={function() { alert('click'); }}>
این جا اشتباه شده. در کامیت بعد درست می‌کنم

2020-11-14 09:04 UTC, amirmahdi-nsh commented on content/tutorial/tutorial.md
> +حالا اگر روی هر مرحله موجود روی تارخچه‌ی بازی کلیک کنیم، صفحه‌ی tic-tac-toe سریعا آپدیت شده و به ما اتفاقاتی که در آن گام افتاده را نشان می‌دهد.
این جا نسخه‌ی انگیلیسی معنی متفاوتی دارد. که نمی‌دانم به فارسی چه‌گونه باید ترجمه شود

2020-11-14 09:10 UTC, amirmahdi-nsh commented on content/tutorial/tutorial.md
> +بر گرفته از [نسخه‌ی انگلیسی](https://reactjs.org/tutorial/tutorial.html) - همراه با تغییرات برای درک بهتر مطالب توسط پارسی زبانان عزیز - مترجم اصلی: امیرمهدی نژادشمسی
اگر تشخیص می‌دهید که نباید این وجود داشته باشد می‌تواند آن را پاک کنید

2020-11-14 09:26 UTC, amirmahdi-nsh commented on content/tutorial/tutorial.md
> -We'll get to the funny XML-like tags soon. We use components to tell React what we want to see on the screen. When our data changes, React will efficiently update and re-render our components.
این خط را در نسخه‌ی فارسی نیاورده‌ام زیرا که اگر دقت کنید
در کد بالا JSX یعنی استفاده از کدها شبیه XML به جای ساخت اشیاء ری‌اکت آمده اما
اما این جمله گفته که به کد‌های شبه XML خواهیم رسید!! در صورتی که رسیده‌ایم.

2021-01-17 18:02 UTC, amirmahdi-nsh commented
سلام، اگر ممکنه این قسمت‌هایی نشانه گذاری کردم رو تصمیم گیری کنید به چه نحوی باشه.
منظورم اینه که فقط شما بفرمایید این قسمت‌ها هر کدام وجود داشته باشد یا نه و من بقیه‌ی اصلاح‌ها رو انجام بدم.
همچنین بعد از چند دور چک کردن مشکلات ریزی رو پیدا کردم که اون‌ها هم باید تصحیح کنم
ممنون

2021-01-24 17:26 UTC, sorousht requested changes
<p dir="rtl">
@amirmahdi-nsh جان
</p>
<p dir="rtl">
ببخشید که دیر جواب دادم. به سوال ها پاسخ دادم و همان طور که احتمالا پیش بینی می کردید، نظم این بوده که چیزی اضافه و کم نشود. من متوجه هستم که تغییراتی که در متن اضافه کردید، فهم موضوع رو برای خودتون راحت تر کرده است، اما شاید اینجا برای انتشار آن جای درستی نباشد و بهتر باشه اون مواردی رو که فکر می کنید باید تغییر کند به نسخه اصلی پیشنهاد بدهید، یا به صورت یک پست بلاگ شخصی منتشر شود. زییرا اینجا فقط هدف ما ترجمه است و تغییر دلخواه آن طبق سلیقه مشارکت کنندگان نگهداری از این پروژه را بسیار دشوار کرده و در‌آینده دیگر شباهتی با متن اصلی نخواهد داشت.
</p>
<p dir="rtl">
به هر حال پیشنهاد من این است که حیف زحمت و قت شماست که رها شود. اگر اصلاحات رو انجام بدهید، بسیار مشتاقم که زودتر پرونده این صفحه بسته شود.
</p>

2021-01-24 17:26 UTC, sorousht commented on content/tutorial/tutorial.md
> +بر گرفته از [نسخه‌ی انگلیسی](https://reactjs.org/tutorial/tutorial.html) - همراه با تغییرات برای درک بهتر مطالب توسط پارسی زبانان عزیز - مترجم اصلی: امیرمهدی نژادشمسی
لطفا این قسمت حذف شود.

2021-01-24 17:26 UTC, sorousht commented on content/tutorial/tutorial.md
> +اگر وقت اضافه دارید و یا می‌خواهید مهارت خودتان را در ری‌اکت بسنجید، اینجا چند ایده برای بهبود این بازی وجود دارد که از راحت به سخت مرتب شده‌اند:
مشکلی نیست.

2021-01-24 17:26 UTC, sorousht commented on content/tutorial/tutorial.md
> +حالا اگر روی هر مرحله موجود روی تارخچه‌ی بازی کلیک کنیم، صفحه‌ی tic-tac-toe سریعا آپدیت شده و به ما اتفاقاتی که در آن گام افتاده را نشان می‌دهد.
بنظرم درست ترجمه شده.

2021-01-24 17:26 UTC, sorousht commented on content/tutorial/tutorial.md
> +در مثال بالا، ماشین از ابتدای لیست مورد نظر شروع می‌کند و آن را درون تابعی دلخواه را درون تابع داده شده قرار می‌دهد (در اینجا این تابع `x => x * 2` است که یک مقدار گرفته و دو برابر آن در خروجی بر می‌
لطفا توضیحات اضافه حذف شود.

2021-01-24 17:26 UTC, sorousht commented on content/tutorial/tutorial.md
> +اگر کنجکاو هستید میتوانید در متد `handleClick` به جای کد قبلی عبارت `'this.state.squares[i] = 'X;` قرار دهید. مشاهده خواهید کرد بعد از فشردن مربع‌ها هیچ تغییری ایجاد نمی‌شود ولی اگر در تب components،
شکی نیست که توضیح شما کمک می کند به خواننده ولی از نظر حرفه‌ای و اخلاقی درست نیست که به متن چیزی اضافه و کم شود. خواهش می کنم این بخش را هم حذف کنید.

2021-01-24 17:26 UTC, sorousht commented on content/tutorial/tutorial.md
> +#### تشخیص تغییرات {#determining-when-to-re-render-in-react}
درست نیست که این مثال و توضیحات که بخشی از کنجکاوی شخصی شما بوده به این متن اضافه بشود. خواهش می کنم حذف شود.

2021-01-24 17:26 UTC, sorousht commented on content/tutorial/tutorial.md
> +>نکته
لطفا شیوه نگارش نسخه اصلی رو دنبال کنید

2021-01-24 17:26 UTC, sorousht commented on content/tutorial/tutorial.md
> -We'll get to the funny XML-like tags soon. We use components to tell React what we want to see on the screen. When our data changes, React will efficiently update and re-render our components.
فکر کنم منظورش اینه که به زودی به بررسی عمیق تر اون بخش می رسیم

2021-01-24 17:26 UTC, sorousht commented on content/tutorial/tutorial.md
> -We'll get to the funny XML-like tags soon. We use components to tell React what we want to see on the screen. When our data changes, React will efficiently update and re-render our components.
بهتره که نگه داشته شود

2021-03-07 18:20 UTC, sorousht commented
<p dir="rtl">
سلام @amirmahdi-nsh جان، امیدوارم جال شما خوب باشه. @seven-deuce برای تکمیل کار شما اعلام آمادگی کرده است. از نظر شما مشکلی نیست؟
</p>

2021-03-07 19:15 UTC, amirmahdi-nsh commented
> سلام @amirmahdi-nsh جان، امیدوارم جال شما خوب باشه. @seven-deuce برای تکمیل کار شما اعلام آمادگی کرده است. از نظر شما مشکلی نیست؟

سلام، ممنون از شما و دوست عزیز که لطف دارن. ببخشید دیر شد تقریبا دیگه آخراشه مشکلی خاصی هم پیش‌نیومده فقط یکم کار‌های غیر منتظره برام ایجاد شده، برای متن نیاز به کمک نیست و تلاش میکنم حداکثر تا یه هفته دیگه کاملا تمام ویراستاری‌ها رو تمام کنم و فایل نهایی رو آپلود کنم
ممنونم

2021-03-14 11:53 UTC, amirmahdi-nsh commented on content/tutorial/tutorial.md
>  **موفق باشید**
به نظرتون «موفق باشید» در آخر متن نوشته بشه؟

2021-03-14 11:54 UTC, amirmahdi-nsh commented on content/tutorial/tutorial.md
> +اگر به مشکل برخوردید به [منابع کمکی کامیونیتی](https://reactjs.org/community/support.html) رجوع کنید. در مواقع خاص [Reactiflux Chat](https://discord.gg/reactiflux) و [انجمن ری‌اکت فارسی](https://reac
به نظرتون از انجمن ری‌اکت ایران نام برده بشه یا خیر؟

2021-03-14 12:08 UTC, amirmahdi-nsh commented
<p dir='rtl' align='right'>
سلام، سروش عزیز @sorousht. متن میشه گفت متن کامله و تمام مشکلات و ویراستیاری‌های ممکن رو انجام دادم. در خصوص جاهایی که گفته بودید پاک کنم نیز حذف شده و فقط در جاهایی که فکر میکردم ممکن است به رساندن معنا صدمه‌ی زیادی وارد کند بسیار خلاصه کرده و درون [] قرار دادم.
فکر می‌کنم بعد از انجام این چند قسمت که علامت‌گذاری کردم، متن کاملا آماده‌ی قرار داشتن باشه 
</p>

2021-07-17 14:29 UTC, sJJdGG commented
<div align="right" dir="rtl">
سلام @amirmahdi-nsh 

اگه امکانش هست میتونی یه rebase به master بدی تا زودتر این پیج بررسی نهایی بشه؟
</div>

2021-07-20 18:01 UTC, amirmahdi-nsh commented
<p dir='rtl' align='right'>
@sJJdGG سلام، تلاش کردم ولی به conflictهای زیادی می‌خوره که لازمه هر کامیت به کامیت حل بشن و یکم سخت میشه 
اگه مشکلی نیست من کامیت‌های قبلی رو کلا پاک کنم و فقط فایل نهایی رو توی یه کامیت بذارم
</p>

2021-08-11 12:05 UTC, sJJdGG approved these changes
LGTM

2021-08-11 12:06 UTC, merged

2021-08-13 18:27 UTC, amirmahdi-nsh commented
<p dir='rtl' align='right'>@sJJdGG
مطالب توی سایت قرار گرفت و بسیار ممنون از وقت و زمانی که گذاشتید و مشکلات زیادی که متن داشت رو برطرف کردین. فکر نمی‌کردم تا این حد غلط‌های نگارشی داشته باشه 
</p>
<p dir='rtl' align='right'>
همچنین از سروش عزیز هم تشکر میکنم که بسیار کمک کرد @sorousht 
</p>

2021-08-13 20:03 UTC, sJJdGG commented
@amirmahdi-nsh 
<div align="right" dir="rtl">
کار گروهیه :)
ممنون ازت که توی این همه مدت بیخیالش نشدی
</div>