translate react v17.0.0 to persian
reactjs/fa.reactjs.org pull request #183
Opened 2020-11-17 15:00 UTC by pooooriya

2020-11-19 09:42 UTC, pooooriya commented
اگر مقدور هست این مورد رو به علت تازگی مطلب و اشتیاق توسعه دهندگان ایرانی برای فراگیری موراد جدیدی ری اکت 17 زودتر بررسی یفرمایید ضمنا از لطف و اعتماد جنابعالی به بنده بسیار مسرورم

2020-11-21 17:31 UTC, sorousht requested changes

2020-11-21 17:31 UTC, sorousht commented on content/blog/2020-10-20-react-v17.md
> +ما یک [مثال در مخزن](https://github.com/reactjs/react-gradual-upgrade-demo/) آماده کرده ایم که چگونه یک نسخه قدیمی از ری اکت را اگر لازم است به شکل lazy load اجرا کنید. این پیش نمایش از Create React
```suggestion
ما یک [مخزن کد نمونه](https://github.com/reactjs/react-gradual-upgrade-demo/) آماده کرده‌ایم که چگونه یک نسخه قدیمی از ری‌اکت را اگر لازم است به شکل lazy-load اجرا کنید. این مثال از Create React App استفاده می‌کند. اما با دیگر راهکارهای مشابه که از ابزار های دیگری استفاده می‌کنند نیز این امر ممکن است، ما از دیگر مقال‌هایی که با ابزار‌های دیگر به عنوان pull request برای ما ارسال شود، استقبال می‌کنیم.
```

2020-11-21 17:31 UTC, sorousht commented on content/blog/2020-10-20-react-v17.md
> +>ما **تغییرات دیگر را** به بعد از نسخه 17 ری اکت به موکول کرده ایم. هدف از انتشار این نسخه فعال کردن قابلیت ارتقا تدریجی است . اگر ارتقا به ری اکت 17 پیچیده شود هدف آن با شکست روبرو خواهد شد.
```suggestion
>ما **تغییرات دیگر را** به بعد از ری‌اکت ۱۷ موکول کرده‌ایم. هدف از انتشار این نسخه فعال کردن قابلیت ارتقا تدریجی است. اگر ارتقا به ری اکت ۱۷ پیچیده شود هدف آن با شکست روبرو خواهد شد.
```

2020-11-21 17:31 UTC, sorousht commented on content/blog/2020-10-20-react-v17.md
> +## تغییر در محول کننده رویداد ها
```suggestion
##  تغییراتی در محول کننده رویداد‌ها (event delegation)
```

2020-11-21 17:31 UTC, sorousht commented on content/blog/2020-10-20-react-v17.md
> +برای فعال کردن قابلیت ارتقا تدریجی, ما به کمی تغییر در سیستم رویداد های ری اکت نیاز داشتیم. ری اکت 17 یک انتشار بزرگی  است به این علت که این تغییرات با اهمیت هستند. شما میتوانید  [سوالات متداول مارا
```suggestion
برای فعال کردن قابلیت ارتقا تدریجی، ما به کمی تغییر در سیستم رویدادهای ری‌اکت نیاز داشتیم. ری اکت ۱۷ انتشار یک نسخه major  است به این علت که این تغییرات می‌توانند شکننده باشند. شما می‌توانید [سوالات متداول مارا نسبت به این موضوع](/docs/faq-versioning.html#breaking-changes) را بخوانید تا درباره تعهد ما نسبت به ثبات این تغییرات، اطلاعت لازم را به‌دست آورید.
```

2020-11-21 17:31 UTC, sorousht commented on content/blog/2020-10-20-react-v17.md
> +ری اکت 17 دیگر هیچ رویدادی را به سطح `document`متصل نمیکند. در عوض, آن را به Root DOM  ای که درخت ری اکت از آن رندر میشود ، متصل می گردد:
```suggestion
ری اکت ۱۷ دیگر هیچ یک از event handler ها را به سطح `document`متصل نمی‌کند. در عوض، آن را به [المنت] دربردارنده ریشه DOM که درخت ری اکت از آن رندر می‌شود، متصل می کند:
```

2020-11-21 17:31 UTC, sorousht commented on content/blog/2020-10-20-react-v17.md
> +در ری اکت 16 و قبل تر , ری اکت برای اکثر رویداد هایش از `document.addEventListener()` استفاده میکرد. ری اکت 17 با صدا زدن `rootNode.addEventListener()` این کار را در پشت پرده انجام می دهد.
```suggestion
در ری اکت ۱۶ و قبل‌تر، ری‌اکت برای اکثر رویداد هایش از `document.addEventListener()` استفاده می‌کرد. ری‌اکت ۱۷ با صدا زدن `rootNode.addEventListener()` این کار را در پشت پرده انجام می‌دهد.
```

2020-11-21 17:31 UTC, sorousht commented on content/blog/2020-10-20-react-v17.md
> +![یک دیاگرام که نشان میدهد که چگونه ری اکت 17 رویداد ها را به Root به جای Document متصل میکند](../images/blog/react-v17-rc/react_17_delegation.png)
```suggestion
![یک دیاگرام که نشان می‌دهد که چگونه ری‌اکت ۱۷ رویدادها را به ریشه‌ها به جای document متصل می‌کند](../images/blog/react-v17-rc/react_17_delegation.png)
```

2020-11-21 17:31 UTC, sorousht commented on content/blog/2020-10-20-react-v17.md
> +[در پست معرفی ری اکت 17 نسخه برگزیده انتشار  ،](/blog/2020/08/10/react-v17-rc.html#other-breaking-changes) ما تغییرات اساسی موجود در ری اکت 17 را توضیح داده ایم .
```suggestion
[در پست معرفی ری‌اکت ۱۷ نسخه برگزیده انتشار (rc)](/blog/2020/08/10/react-v17-rc.html#other-breaking-changes) ما تغییرات اساسی موجود در ری اکت ۱۷ را توضیح داده‌ایم .
```

2020-11-21 17:31 UTC, sorousht commented on content/blog/2020-10-20-react-v17.md
> +ما با توجه به تغییرات صورت گرفته تنها مجبور به تغییر کمتر از بیست کامپوننت از صد هزار کامپوننت موجود در FaceBook شدیم, بنابراین **ما انتظار داریم که اکثر اپلیکیشن ها بتواننده بدون مشکل به نسخه 17 از
```suggestion
تا کنون ما با توجه به تغییرات صورت گرفته تنها مجبور به تغییر کمتر از بیست کامپوننت از بیش از ۱۰۰,۰۰۰ کامپوننت موجود در Facebook شده‌ایم. بنابراین **ما انتظار داریم که اکثر برنامه‌ها بتوانند بدون مشکل به نسخه ۱۷ از ری‌اکت ارتقا پیدا کنند**. لطفا اگر به مشکلی برخورد کردید [آن را با ما در میان بگذارید](https://github.com/facebook/react/issues).
```

2020-11-21 17:31 UTC, sorousht commented on content/blog/2020-10-20-react-v17.md
> +ری اکت 17 از [تغییر شکل جدید JSX](/blog/2020/09/22/introducing-the-new-jsx-transform.html) پشتیبانی میکند. ما همچنین در نسخه 16.14.0 و 15.7.0 و 0.14.10 از این قابلیت پشتیبانی خواهیم کرد و به این مورد
```suggestion
ری اکت ۱۷ از [تغییر شکل جدید JSX](/blog/2020/09/22/introducing-the-new-jsx-transform.html) پشتیبانی می‌کند. ما همچنین در نسخه ۱۶.۱۴۰ و ۱۵.۷.۰ و ۰.۱۴.۱۰ از این قابلیت پشتیبانی خواهیم کرد. به این مورد توجه کنید که این قابلیت کاملا اختیاری است و شما مجبور به استفاده از آن نیستید. تغییر شکل قبلی JSX را می‌توانید همچنان استفاده کنید و برنامه‌ای برای حذف پشتیبانی از آن وجود ندارد .
```

2020-11-21 17:31 UTC, sorousht commented on content/blog/2020-10-20-react-v17.md
> +ری اکت نیتیو برنامه زمانی مشخصی برای انتشار دارد. ما در حال حاضر انتظار پشتیبانی از ری اکت 17 برای استفاده در ری اکت نیتیو 0.65 داریم ، اما نسخه دقیق آن باید تغییر کند . مثل همیشه شما میتوانید بحث ها
```suggestion
ری‌اکت نیتیو برنامه زمانی مشخصی برای انتشار دارد. ما در حال حاضر انتظار پشتیبانی از ری اکت ۱۷ برای استفاده در ری اکت نیتیو ۰.۶۵ داریم، اما نسخه دقیق آن باید تغییر کند. مثل همیشه شما می‌توانید بحث‌های مربوط به انتشار ری‌اکت نیتیو را در انجمن مربوط به آن [پیگیری کنید](https://github.com/react-native-community/releases).
```

2020-11-21 17:34 UTC, sorousht commented
<p dir="rtl">سلام @pooooriya عزیز</p>
<p dir="rtl">ممنون از زحمتی که برای ترجمه این صفحه کشیدید. من  تمام تلاشم را کردم که در اولین فرصت بررسی کنم و نظراتم را نوشتم. به جز چند مورد کوچک که ترجمه رسا نبود، دیگر موارد بیشتر نگارشی بودند</p>

<p dir="rtl">پس از اصلاح موارد پیشنهاد شده، این ترجمه رو منتشر می‌کنیم :)</p>
<p dir="rtl">ارادتمند، سروش</p>

2020-11-22 19:51 UTC, pooooriya commented
ممنون از زمانی که گذاشتین و این موارد رو چک کردین تمامی موارد تایید شد ! سپاس از زحماتتان
ارادتمند پوریا

2020-11-22 20:42 UTC, sorousht approved these changes

2020-11-22 20:42 UTC, merged